version: '3.8'

services:
  api:
    build: .
    env_file: .env
    ports:
      - 5001:5001
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    env_file: .env
    ports:
      - "5432:5432"

