version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    
  api:
    depends_on:
      - db
    build: .
    volumes:
      - .:/usr/src/app
    env_file: .env
    # command: npm run start:dev
    ports:
      - 8082:8082


